{% set name = "multimethod" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1589bf52ca294667fd15527ea830127c763f5bfc38562e3642591ffd0fd9d56f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - multimethod

about:
  home: https://github.com/coady/multimethod
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Multiple argument dispatching.
  doc_url: https://multimethod.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - albop
